FROM debian:testing
RUN apt-get update && apt-get install -y \
    gcc \
    libnotify-dev \
    make \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*
COPY . /build
RUN cd /build && make clean install
CMD ["batsignal", "-v"]
