.TH BATSIGNAL 1 batsignal\-VERSION
.SH NAME
batsignal \- battery monitor daemon
.SH SYNOPSIS
.B batsignal
.RB [ OPTIONS ]
.SH DESCRIPTION
batsignal is a lightweight battery daemon written in C that notifies the user about low battery states. It is intended for minimal window managers, but can be used in any environment that supports desktop notifications via libnotify.
.SH OPTIONS
.TP
.B \-h
display help
.TP
.B \-v
display version information
.TP
.B \-b
run batsignal as background daemon
.TP
.B \-i
ignore missing battery errors
.TP
.B \-w LEVEL
battery warning LEVEL (default 15). Set to 0 disable this level
.TP
.B \-c LEVEL
critical battery LEVEL (default 5). Set to 0 disable this level
.TP
.B \-d LEVEL
battery danger LEVEL (default 2). Set to 0 disable this level
.TP
.B \-W LEVEL
show MESSAGE when battery is at warning level
.TP
.B \-C LEVEL
show MESSAGE when battery is at critical level
.TP
.B \-D LEVEL
Run COMMAND when battery is at danger level
.TP
.B \-n LEVEL
battery device NAME (default BAT0)
.TP
.B \-m LEVEL
minimum number of SECONDS (default 60) to wait between battery checks
.SH AUTHORS
Written by Corey Hinshaw and Aaron Marcher.
.SH COPYRIGHT
Copyright 2018 Corey Hinshaw
.br
Copyright 2016-2017 Aaron Marcher
.br
License: ISC License - See the LICENSE file for details.
.SH BUGS
See the FIXME's in the code.
